name: Update FanCode Data
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch Data using Advanced Headers
        run: |
          curl -L -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
               -H "X-Platform: web" \
               -H "Origin: https://www.fancode.com" \
               -H "Referer: https://www.fancode.com/" \
               -H "Accept: application/json" \
               "https://www.fancode.com/api/v1/content/home?section=all" > matches.json
          
      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add matches.json
          git commit -m "Automated Match Update" || echo "No changes to commit"
          git push origin main
          
